#!/bin/perl

# Poor man's perl shell.

# Simply type two carriage returns every time you want to evaluate.
# Note that it must be a complete perl statement--don't type double
#  carriage return in the middle of a loop.

$/ = '';	# set paragraph mode
while (<>) {
    eval; print $@ || "\n";
}
